### ISSUE TITLE
Validation & index

### ISSUE THREAD

**Issue by jozefvaclavik** [ruckus/quickbooks-ruby#308]
I hit strange problem yesterday. I tried to push customer without email address. In my method I did something like this:

```
    qbo_customer = Quickbooks::Model::Customer.new
    ...
    email = Quickbooks::Model::EmailAddress.new
    email.address = customer.users.first.try(:email)
    qbo_customer.primary_email_address = email
```

If my customer model doesn't have any users, it will do `email.address = nil` and in this case when I tried to push customer, it crashed [the validation](https://github.com/ruckus/quickbooks-ruby/blob/master/lib/quickbooks/util/name_entity.rb#L25). Here's the backtrace:

```
irb(main):013:0> response = service.create(qbo_new_customer)
NoMethodError: undefined method `index' for nil:NilClass
	from /app/vendor/bundle/ruby/2.2.0/bundler/gems/quickbooks-ruby-339d11765318/lib/quickbooks/util/name_entity.rb:25:in `email_address_is_valid'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:430:in `block in make_lambda'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:190:in `call'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:190:in `block in simple'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `call'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `block in call'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `each'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:502:in `call'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
	from /app/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.3/lib/active_model/validations.rb:395:in `run_validations!'
	from /app/vendor/bundle/ruby/2.2.0/gems/activemodel-4.2.3/lib/active_model/validations.rb:334:in `valid?'
	from /app/vendor/bundle/ruby/2.2.0/bundler/gems/quickbooks-ruby-339d11765318/lib/quickbooks/service/service_crud.rb:42:in `create'
	from (irb):13
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from /app/bin/rails:8:in `require'
	from /app/bin/rails:8:in `<main>'irb(main):014:0>
```

**Comment by jozefvaclavik** [comment]
I did quick fix by doing `email.address = customer.users.first.try(:email).to_s` and let it return validation error. Anyway I think this should not crash in a first place.
