### ISSUE TITLE
System Failure Error: Bad arguments passed

### ISSUE THREAD

**Issue by dlindahl** [ruckus/quickbooks-ruby#39]
When I try to create an Invoice, I am getting the following error:

```
/Users/dlindahl/app/qbo/.bundle/gems/quickbooks-ruby-0.0.5/lib/quickbooks/service/base_service.rb:268:in `parse_and_raise_exception': An application error has occurred while processing your request: (IntuitRequestException)
  System Failure Error: Bad arguments passed to public com.intuit.schema.finance.v3.IntuitResponse com.intuit.qbo.servicev3.rest.Customer.create(java.lang.String,com.intuit.schema.finance.v3.Customer,java.lang.String,java.lang.String,java.lang.String) throws com.intuit.qbo.servicev3.FdmException  ( java.lang.String 1032845425, com.intuit.schema.finance.v3.Invoice com.intuit.schema.finance.v3.Invoice@59687eb7, null, null, null )
  from /Users/dlindahl/app/qbo/.bundle/gems/quickbooks-ruby-0.0.5/lib/quickbooks/service/base_service.rb:255:in `check_response'
  from /Users/dlindahl/app/qbo/.bundle/gems/quickbooks-ruby-0.0.5/lib/quickbooks/service/base_service.rb:228:in `do_http'
  from /Users/dlindahl/app/qbo/.bundle/gems/quickbooks-ruby-0.0.5/lib/quickbooks/service/base_service.rb:194:in `do_http_post'
  from /Users/dlindahl/app/qbo/.bundle/gems/quickbooks-ruby-0.0.5/lib/quickbooks/service/service_crud.rb:17:in `create'
  from /Users/dlindahl/app/qbo/lib/qbo/tasks/invoicing.rb:63:in `create'
  from /Users/dlindahl/app/qbo/.bundle/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
  from /Users/dlindahl/app/qbo/.bundle/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
  from /Users/dlindahl/app/qbo/.bundle/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
  from /Users/dlindahl/app/qbo/.bundle/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
  from bin/qbo:5:in `<main>'
```

Any ideas what I'm missing or might be doing wrong?

The invoice and line item validations return `true` if that helps weed out anything.

**Comment by tayyab-arkhitech** [comment]
Well You are not alone here @dlindah. 😄 
I was also creating PurchaseOrder on a Purchase service. 😶‍🌫️ 
IDK how much hours this thread saved me.
