### ISSUE TITLE
TaxCodeRef rendering within SalesItemLineDetail

### ISSUE THREAD

**Issue by srushe** [ruckus/quickbooks-ruby#427]
I'm seeing an issue when trying to add use `tax_code_ref` on an instance of `SalesItemLineDetail` and I'm not sure whether this is a big or a misunderstanding on my part. I'm attempting to see `TaxCodeRef` to `NON` (as specified in a [recent Intuit blog post](https://developer.intuit.com/hub/blog/2018/03/28/automated-sales-tax-quickbooks-online-api-update)), however I'm receiving an error. I've boiled the issue down to a small script that exhibits the behaviour.

```ruby
require 'quickbooks-ruby'

sales_receipt = Quickbooks::Model::SalesReceipt.new()
sales_receipt.line_items = [
  Quickbooks::Model::Line.new().tap do |line_item|
    line_item.sales_item! do |detail|
      detail.tax_code_ref = 'NON'
    end
  end
]

puts sales_receipt.to_xml_ns
```

Running the above cause the following error to appear...

```
/Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml/xml/references.rb:301:in `block (2 levels) in update_xml': undefined method `to_xml' for "NON":String (NoMethodError)
Did you mean?  to_sym
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml/xml/references.rb:300:in `tap'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml/xml/references.rb:300:in `block in update_xml'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml/xml/references.rb:291:in `tap'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml/xml/references.rb:291:in `update_xml'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml.rb:42:in `block (2 levels) in to_xml'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml.rb:39:in `each'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml.rb:39:in `block in to_xml'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml.rb:35:in `tap'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml.rb:35:in `to_xml'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml/xml/references.rb:298:in `block in update_xml'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml/xml/references.rb:291:in `tap'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml/xml/references.rb:291:in `update_xml'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml.rb:42:in `block (2 levels) in to_xml'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml.rb:39:in `each'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml.rb:39:in `block in to_xml'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml.rb:35:in `tap'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml.rb:35:in `to_xml'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml/xml/references.rb:295:in `block (2 levels) in update_xml'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml/xml/references.rb:294:in `each'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml/xml/references.rb:294:in `block in update_xml'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml/xml/references.rb:291:in `tap'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml/xml/references.rb:291:in `update_xml'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml.rb:42:in `block (2 levels) in to_xml'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml.rb:39:in `each'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml.rb:39:in `block in to_xml'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml.rb:35:in `tap'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/roxml-3.3.1/lib/roxml.rb:35:in `to_xml'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/quickbooks-ruby-0.4.6/lib/quickbooks/model/base_model.rb:19:in `to_xml_inject_ns'
	from /Users/srushe/.rvm/gems/ruby-2.3.7@accounting-sync/gems/quickbooks-ruby-0.4.6/lib/quickbooks/model/base_model.rb:39:in `to_xml_ns'
```

Commenting out the `detail.tax_code_ref = 'NON'` line results in a successful XML generation of (indented for ease of reading)...

```xml
<SalesReceipt xmlns="http://schema.intuit.com/finance/v3" sparse="false">
  <Line>
    <DetailType>SalesItemLineDetail</DetailType>
    <SalesItemLineDetail>
      <UnitPrice>0.0</UnitPrice>
      <Qty>0.0</Qty>
    </SalesItemLineDetail>
  </Line>
</SalesReceipt>
```

Am I using `tax_code_ref` incorrectly in `SalesItemLineDetail`, or is this a bug and should it actually add an entry to the item?

**Comment by ruckus** [comment]
When you use a setter that ends in `_ref` like you do here:

```ruby
detail.tax_code_ref = 'NON'
```

the gem expects that the right-side is a Quickbooks Model-like object.

In your case you are attempting to assign just a String.

Solution: wrap your string value in a `BaseReference` object,

```ruby
detail.tax_code_ref = Quickbooks::Model::BaseReference.new('NON')
```

**Comment by srushe** [comment]
Aha! Thanks very much for clearing that up @ruckus. Makes sense now that you mention it. Appreciate the response 🥇
